### ISSUE TITLE
Update packages to latest

### ISSUE THREAD

**Issue by bluepuma77** [khromov/sveltekit-capacitor-starter#4]
Tried to get this up and running, but with those bleeding edge frameworks there are always a lot of changes:
```
SvelteKit   1 -> 2
Vite        4 -> 5
```
I updated packages with `ncu -u` ([link](https://www.npmjs.com/package/npm-check-updates)) and the whole project broke. 

Could you provide an updated "starter kit"?

**Comment by khromov** [comment]
If you want to upgrade the existing project you will need to follow the [SvelteKit 1 to 2 upgrade guide](https://kit.svelte.dev/docs/migrating-to-sveltekit-2). 

But instead I recommend you start a new SvelteKit project on the latest version, [follow the official Capacitor guide](https://capacitorjs.com/docs/getting-started/environment-setup) and then cross-reference with this project configuration if you run into any issues. Unfortunately I don't have the bandwidth to keep these templates up-to-date.
