### ISSUE TITLE
How to set server URL for Capacitor?

### ISSUE THREAD

**Issue by bluepuma77** [khromov/sveltekit-capacitor-starter#6]
I just worked my way through your [great post](https://khromov.se/how-i-published-a-gratitude-journaling-app-for-ios-and-android-using-sveltekit-and-capacitor/), but this is still unclear to me. Can I have the web SvelteKit version just work as is, and add a target domain to the Capacitor static build? Is there a default ENV var for this to get automatic data loading even in Capacitor, or do I need to code everything manually in the fetch myself?

**Comment by khromov** [comment]
👋 If your question is whether you can just point a Capacitor app to the production web version of your site then you can technically do that with `server.url` in `capacitor.config.ts`, however, this is not the intended way to use Capacitor, and you might have problems with app review. The intended way to make a Capacitor app is to package the build output (in our case using adapter-static) into the app itself, not point the app at a URL. `server.url` should only be used in development for HMR.

See also:
https://github.com/ionic-team/capacitor/discussions/4080

**Comment by bluepuma77** [comment]
@khromov Sorry for being late and coming again. So I can not just use `adapter-static` and still use the integrated functionality of fetching data from the SvelteKit backend? 

With regular SvelteKit I just write my database fetch in `+page.server.ts` and Svelte automatically builds the fetching into the page, so data is simply available on `+page.svelte`. 

My idea was to have a start page, login page, and then use "auto-fetching" on a couple of list pages, just supply the backend URL. So this is not possible with capacitor and `adapter-static`, I need to manually create fetch functions?

**Comment by khromov** [comment]
I've written a lot about the limitations, I suggest you check out these two blog posts:
https://khromov.se/how-i-published-a-gratitude-journaling-app-for-ios-and-android-using-sveltekit-and-capacitor/
https://khromov.se/the-missing-guide-to-understanding-adapter-static-in-sveltekit/

The first outlines a hybrid architecture you can do to share the same codebase between Capacitor and web (where you can also implement your backend parts using +server.ts) and the second goes into detail about adapter-static limitations.

Perhaps there is some other way to do it I am unaware of, if you find it you are welcome to share.
