### ISSUE TITLE
question: use plain svelte?

### ISSUE THREAD

**Issue by mustafa0x** [khromov/sveltekit-capacitor-starter#7]
Hi khromov, thanks for this repo!

Quick question if you don't mind. I'm considering using plain Svelte instead. For a few reasons, one being the [multiple-files perf issue](https://github.com/sveltejs/kit/issues/3882#issuecomment-1511976400) you mentioned. Do you have any thoughts on using plain Svelte?

Much appreciated!

**Comment by khromov** [comment]
Hi! No issue to use plain Svelte (Capacitor works as long as you have `index.html` file!).

That being said, there are so many nice features in SvelteKit like routing, data loading and [view transitions](https://svelte.dev/blog/view-transitions) that I would still advocate to use Kit even though it might be slightly slower to start up than a vanilla Svelte project. 

PS.
Capacitor 6 introduces `https` support for Android. I haven't tested it yet but in theory it could alleviate some of the issues.
https://ionic.io/blog/announcing-capacitor-6-0

**Comment by mustafa0x** [comment]
Thanks @khromov for the reply. I think I can reproduce the features you mentioned in plain Svelte. Thanks again!
